server:
  port: 8081

info:
  component: Edge Service (Zuul)

endpoints:
 restart:
  enabled: true
 shutdown:
  enabled: true
 health:
  sensitive: false

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
   productapiservice: /product/**

eureka:
 instance:
  preferIpAddress: true
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/

spring:
 rabbitmq:
  addresses: ${vcap.services.${PREFIX:}rabbitmq.credentials.uri:amqp://${RABBITMQ_HOST:localhost}:${RABBITMQ_PORT:5672}}
