server:
  port: 8082

info:
  component: Product API Service

---
spring:
  profiles: dev
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  user:
    password: password
