server:
 port: 8084

info:
  component: Product Service

 ---
 spring:
   profiles: dev
 eureka:
   instance:
     preferIpAddress: true
   client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
